# Cửa sổ nên nổi thay vì bị tile
# (pavucontrol đã có rule sẵn trong /usr/share/sway/config.d)

for_window [app_id="nm-connection-editor"] floating enable, move position center
for_window [app_id="blueman-manager"] floating enable, move position center

# Hộp thoại (mở file, lưu file, xác nhận...)
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="dialog"] floating enable
for_window [window_type="dialog"] floating enable
for_window [app_id="xdg-desktop-portal-gtk"] floating enable, move position center

# Firefox Picture-in-Picture
for_window [title="^Picture-in-Picture$"] floating enable, sticky enable
