# Khoá màn hình
bindsym $mod+Escape exec swaylock -f

# Không làm phiền (mako)
bindsym $mod+n exec makoctl mode -t do-not-disturb && pkill -RTMIN+8 waybar

# Power menu (rofi)
bindsym $mod+Shift+p exec ~/.config/rofi/powermenu.sh
